#!/usr/bin/env python3
"""Regenerate the ms-rust skill from Microsoft's published guidelines.

Downloads the combined guidelines file, splits it into one file per section, and records a
sha256 so a refresh that changes nothing is visibly a no-op.

The generator lives in the repo on purpose: a skill whose refresh procedure is "run the
upstream generator from somewhere else" drifts the moment that somewhere else changes. Run
it with `pixi run ms-rust-refresh`.

Section names come from the source, not from a hardcoded list. Upstream reorganises -
`Safety` became `Correctness`, and `Macros` and `Project` were added - and a hardcoded list
would silently drop a section rather than fail.
"""

from __future__ import annotations

import hashlib
import re
import sys
import urllib.request
from pathlib import Path

SOURCE = "https://microsoft.github.io/rust-guidelines/agents/all.txt"
HERE = Path(__file__).resolve().parent

# A real section heading is `# Title` followed within a few lines by a `## ` rule heading.
# `# ...` also appears as a Rust comment inside code fences, which is why the shape of what
# follows decides rather than the line alone.
SECTION = re.compile(r"^# ([A-Z].*)$")
RULE_NEARBY = re.compile(r"^## ", re.M)


def slug(title: str) -> str:
    """`Libraries / UX Guidelines` -> `libraries_ux_guidelines`."""
    s = title.lower().replace("/", " ")
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


def sections(text: str) -> list[tuple[str, str]]:
    """Split into (title, body), preserving order and dropping the file's own preamble."""
    lines = text.split("\n")
    starts: list[tuple[int, str]] = []
    for i, line in enumerate(lines):
        m = SECTION.match(line)
        if not m:
            continue
        if RULE_NEARBY.search("\n".join(lines[i + 1 : i + 6])):
            starts.append((i, m.group(1).strip()))

    out: list[tuple[str, str]] = []
    for n, (start, title) in enumerate(starts):
        end = starts[n + 1][0] if n + 1 < len(starts) else len(lines)
        body = "\n".join(lines[start:end]).rstrip() + "\n"
        out.append((title, body))
    return out


LICENCE = (
    "<!-- The Pragmatic Rust Guidelines are copyright (c) Microsoft Corporation, "
    "licensed under the MIT license. Generated by generate.py; do not edit. -->\n\n"
)


def fetch(argv: list[str]) -> bytes:
    """The guidelines, from the network or from a file already fetched.

    `--from-file` exists because a network without direct egress cannot reach the source, and
    a generator that only works with egress is a generator that stops being run. Fetch it
    however your network allows, then pass the path.
    """
    if "--from-file" in argv:
        path = argv[argv.index("--from-file") + 1]
        return Path(path).read_bytes()
    with urllib.request.urlopen(SOURCE, timeout=120) as response:  # noqa: S310 - fixed https URL
        return response.read()


def main(argv: list[str]) -> int:
    try:
        raw = fetch(argv)
    except (OSError, IndexError) as exc:
        print(f"ms-rust: could not read the guidelines: {exc}", file=sys.stderr)
        print(f"  Fetch {SOURCE} by other means and pass --from-file <path>.", file=sys.stderr)
        return 1
    digest = hashlib.sha256(raw).hexdigest()

    stamp = HERE / "all.txt.sha256"
    previous = stamp.read_text(encoding="utf-8").strip() if stamp.is_file() else ""
    if previous == digest:
        print(f"ms-rust: unchanged ({digest[:12]})")
        return 0

    text = raw.decode("utf-8")
    found = sections(text)
    if not found:
        print("ms-rust: no sections found - upstream format changed", file=sys.stderr)
        return 1

    for old in HERE.glob("[0-9][0-9]_*.md"):
        old.unlink()

    for n, (title, body) in enumerate(found, start=1):
        path = HERE / f"{n:02d}_{slug(title)}.md"
        path.write_text(LICENCE + body, encoding="utf-8", newline="\n")
        print(f"  {path.name}  ({body.count(chr(10))} lines)  {title}")

    stamp.write_text(digest + "\n", encoding="utf-8", newline="\n")
    print(f"ms-rust: {len(found)} section(s), sha256 {digest[:12]}")
    print("Update the compliance date in SKILL.md and its file table if sections changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
