//! One acceptance cell for `docs/adr/0029`'s `BigQuery` slice, split out when it took `acceptance.rs`
//! past the 1000-line ceiling `cargo xtask max-lines` enforces. `super::warehouse` and the fixture
//! helpers `acceptance.rs` already builds are reached from here exactly as every other cell in that
//! file reaches them.

use sutura_domain::plan::Executable;
use sutura_domain::warehouse::Warehouse as _;
use sutura_domain::warehouse::deadline::{Budget, Deadline};
use sutura_exec_bigquery::BigQueryError;
use sutura_exec_bigquery::wire::WireError;

use crate::fixture::{Fixture, plan};
use crate::support::presented;

#[test]
#[ignore = "needs a real BigQuery project, named in the developer's own environment"]
fn a_deliberately_slow_statement_is_stopped_at_its_jobtimeoutms() {
    // **The one cell in this repository that measures `docs/adr/0029`'s BigQuery row against a
    // real endpoint, rather than a fake transport.** `crate::wire::WireError::NotComplete`'s own
    // doc names this cell as the confirmation its `deadline_exceeded` mapping needs; if the
    // service's reply for a job stopped at `jobTimeoutMs` is some OTHER shape - a `Refused` with
    // a `stopped` reason, a `jobComplete: true` with an error in `errors[]`, anything this crate
    // does not already treat as `deadline_exceeded` - this assertion fails LOUDLY, which is the
    // point: a predicate written against the documented shape and never checked against the
    // service is a rule with no mechanism.
    //
    // **What "deliberately slow" means here, and its own limit.** This asks the fixture's own
    // decade-wide `SUM`, the same statement every other cell in this file submits, under a
    // two-second port `Deadline` rather than the sixty-second one every other cell uses. Whether
    // that statement genuinely outruns two seconds - and so exercises the SERVICE cancelling the
    // job at `jobTimeoutMs` rather than this adapter's own pre-send `DeadlineSpent` guard firing
    // on a slow token exchange - depends on the developer's own fixture table and network path,
    // neither of which this repository controls. Both outcomes satisfy the assertion below
    // (`deadline_exceeded` answers `true` either way), and the log line names which one fired, so
    // a developer reading a green run can tell which half of the claim it measured.
    let fixture = Fixture::required();
    let table = fixture.unqualified();
    let warehouse = super::warehouse(fixture);
    let plan = plan(&table);
    let tight = Deadline::opened_at(
        std::time::Instant::now(),
        Budget::parse(std::time::Duration::from_secs(2)).expect("2s"),
    );

    let outcome = warehouse.execute(Executable::Query(&plan), &presented(), tight);
    match outcome {
        Ok(rows) => panic!(
            "the statement finished inside a two-second budget and this cell measured nothing \
             about `jobTimeoutMs` - widen the range in `fixture::labelled_plan` or point \
             SUTURA_BQ_TABLE at a larger table: {} row(s) returned",
            rows.rows().len()
        ),
        Err(ref error) => {
            println!(
                "bigquery-acceptance: a two-second budget produced {}",
                match error {
                    BigQueryError::Endpoint {
                        cause: WireError::DeadlineSpent { .. },
                    } => "DeadlineSpent (the pre-send guard fired, so the service was never asked)",
                    BigQueryError::Endpoint {
                        cause: WireError::NotComplete { .. },
                    } => "NotComplete (the documented jobTimeoutMs shape)",
                    _ => "an error this cell does not recognise - see it printed below",
                }
            );
            assert!(
                warehouse.deadline_exceeded(error),
                "a job given a two-second budget over a statement generated by this repository \
                 did not map to `deadline_exceeded` - the reply shape docs/adr/0029 asked this \
                 cell to measure disagrees with what `WireError::NotComplete`'s doc documents: {error:?}"
            );
        }
    }
}
