//! The committed, gated third-party attribution document.
//!
//! WHY A COMMITTED DOCUMENT AT ALL. A release publishes signed binaries and signed, precise,
//! per-binary SBOMs (read out of the `cargo auditable` section). Neither is an attribution
//! statement: an SBOM inventories what ONE binary carries, and an auditor asking "what third-party
//! code is this release permitted to carry" wants a statement over the whole release, in the
//! direction that errs safe. `THIRD_PARTY_NOTICES` is that statement: every crate the workspace's
//! `Cargo.lock` resolves, with its version, under a header that says what the list is and is not.
//! `docs/adr/0021`'s amendment is the decision; this is the mechanism it chose (committed and
//! regenerated by a gate, like every other generated artefact this repository owns).
//!
//! WHY `Cargo.lock` HERE WHEN THE SBOM EDITS IT OUT. The SBOM is an INVENTORY: it must name what
//! a binary actually links, so `Cargo.lock` is the wrong source for it and the auditable section
//! is the right one. Attribution is the opposite direction: it errs toward the whole set, because
//! failing to attribute a crate a release could carry is the failure an auditor disproves, and
//! naming more than any one binary links is safe where naming less is not. One owner per artefact:
//! the SBOM is the auditable binary's, this document is the lock file's.
//!
//! WHY THIS GATE IS CHEAP. It reads `Cargo.lock` as text, renders the list, and diffs it against
//! the committed file - no compiler, no network, no registry cache. A licence identifier is NOT in
//! the lock file and cannot be resolved inside the nix sandbox, which is why this document names
//! crates and versions and points at `deny.toml` and the scheduled ORT review for the identifier
//! and the verdict. Stated in the document's own header as well as here.

use std::collections::BTreeSet;

use crate::Verdict;
use crate::arrow_major;
use crate::repo;

/// The committed document, relative to the repo root.
const DOC: &str = "THIRD_PARTY_NOTICES";

/// The header. Kept as one literal so the gate and the file it generates cannot disagree about
/// what the document claims.
const HEADER: &str = "\
sutura
Copyright the sutura authors

Licensed under the Apache License, Version 2.0 (the \"License\"); see LICENSE.

Third-party dependencies
------------------------

This document lists every crate the workspace's Cargo.lock resolves, with the
version resolved at this commit. It is generated from Cargo.lock by
`cargo xtask check-attribution --fix`, checked unchanged by `cargo xtask
check-attribution`, and shipped - and signed - with every release.

It errs toward the whole resolved set on purpose. An SBOM inventories what one
binary links and must be precise; attribution is the opposite direction, because
failing to name a crate a release could carry is the failure an auditor disproves,
and naming more than any one binary links is safe where naming less is not. The
per-identifier policy is deny.toml's allowlist; cargo deny and the scheduled ORT
licence review are how a licence gets past review. What this file does not state is
a meaning about a crate: it is an inventory, not a verdict.

name version
";

/// Render the document from a lock file. Deterministic: a `BTreeSet` sorts and deduplicates by
/// the rendered `name version` line, so a dependency bump is one added line and nothing moves.
fn render(lock: &str) -> String {
    let crates: BTreeSet<String> = arrow_major::packages(lock)
        .iter()
        .map(|p| format!("{} {}", p.name, p.version))
        .collect();
    let mut document = String::from(HEADER);
    for entry in &crates {
        document.push_str(entry);
        document.push('\n');
    }
    document
}

pub(crate) fn run(args: &[String]) -> Verdict {
    let fix = args.iter().any(|a| a == "--fix");
    let Some(root) = repo::root() else {
        eprintln!("xtask check-attribution: could not determine the repo root");
        return Verdict::Fail;
    };
    let Ok(lock) = std::fs::read_to_string(root.join("Cargo.lock")) else {
        eprintln!("xtask check-attribution: could not read Cargo.lock");
        return Verdict::Fail;
    };
    let count = arrow_major::packages(&lock).len();
    let wanted = render(&lock);
    let path = root.join(DOC);

    if fix {
        let Ok(mut written) = std::fs::File::create(&path) else {
            eprintln!("xtask check-attribution: could not write {DOC}");
            return Verdict::Fail;
        };
        if std::io::Write::write_all(&mut written, wanted.as_bytes()).is_err() {
            eprintln!("xtask check-attribution: could not write {DOC}");
            return Verdict::Fail;
        }
        println!("xtask check-attribution: wrote {DOC} with {count} crates");
        return Verdict::Pass;
    }

    let Ok(committed) = std::fs::read_to_string(&path) else {
        eprintln!("xtask check-attribution: FAILED - {DOC} does not exist in the tree");
        eprintln!("  run `cargo xtask check-attribution --fix` to generate it ({count} crates)");
        return Verdict::Fail;
    };

    if committed == wanted {
        println!("xtask check-attribution: ok - {DOC} names all {count} crates in Cargo.lock");
        return Verdict::Pass;
    }

    let out_of_date: Vec<String> = arrow_major::packages(&lock)
        .iter()
        .map(|p| format!("{} {}", p.name, p.version))
        .filter(|rendered| !committed.lines().any(|l| l == rendered.as_str()))
        .collect();

    eprintln!("xtask check-attribution: FAILED - {DOC} does not match Cargo.lock");
    if out_of_date.is_empty() {
        eprintln!("  no crate is missing; the file is out of date rather than short");
    } else {
        eprintln!("  missing from {DOC}:");
        for entry in out_of_date.iter().take(10) {
            eprintln!("    {entry}");
        }
        if out_of_date.len() > 10 {
            eprintln!("    ... and {} more", out_of_date.len() - 10);
        }
    }
    eprintln!("  run `cargo xtask check-attribution --fix` to regenerate {DOC}");
    Verdict::Fail
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn two_crates_render_sorted_and_deduplicated() {
        let lock = "name = \"zebra\"\nversion = \"2.0.0\"\nname = \"alpha\"\nversion = \"1.0.0\"\nname = \"alpha\"\nversion = \"1.0.0\"\n";
        let document = render(lock);
        assert!(document.contains("alpha 1.0.0"));
        assert!(document.contains("zebra 2.0.0"));
        // dedup: one alpha line.
        assert_eq!(document.matches("alpha 1.0.0").count(), 1);
        // sorted: alpha before zebra.
        assert!(document.find("alpha 1.0.0").unwrap() < document.find("zebra 2.0.0").unwrap());
    }

    #[test]
    fn a_version_line_without_a_name_is_not_a_crate() {
        let lock = "version = \"3\"\nname = \"real\"\nversion = \"1.0.0\"\n";
        let document = render(lock);
        assert!(!document.contains(" 3"));
        assert!(document.contains("real 1.0.0"));
    }
}
