//! The unauthenticated token boundary: arbitrary bytes presented as a bearer token.
//!
//! **The boundary.** This is the earliest untrusted input in the process - an unauthenticated
//! caller's bytes, read before anything has been verified. `TokenValidator::key_id` is an
//! associated function precisely because nothing configured applies yet, and it runs base64url and
//! JSON over that input to get a key id.
//!
//! **What is asserted beyond "did not abort".** That `verify` never returns `Ok`. The verifying key
//! below is public material whose private half was generated for this file and discarded, so no
//! byte string a fuzzer produces can carry a signature over it: a generated input that verified
//! would be a signature-verification bypass, and this target is searching for one.
//!
//! **What this does NOT cover, and the reason is structural rather than an omission.** Everything
//! `verify` does *after* the signature check - the `Claims` deserialization, the `typ` class check,
//! the actor-chain nesting bound, `SubjectId::parse` on the `sub` claim - is behind a valid
//! signature, and generated bytes cannot cross it. Reaching that half needs a harness holding a
//! *fixed* signing key, because a crash artifact has to reproduce on the next run, and a fixed
//! private key in a public repository is a committed private key. So the newtypes that half applies
//! to caller-controlled claim text are fuzzed directly below instead, and the claims
//! *deserialization* is uncovered. It is named here rather than implied by a green run.

#![no_main]

use libfuzzer_sys::fuzz_target;
use sutura_config::{
    InboundIdentity, IssuerUrl, KeySetFile, PinnedAlgorithms, RequiredTokenType, ResourceIdentifier, SigningAlgorithm,
};
use sutura_domain::identity::{Actor, SubjectId};
use sutura_http::inbound::keys::{KeyId, KeySet};
use sutura_http::inbound::token::TokenValidator;

/// A verifying key, in the shape the deployment reads one.
///
/// **Public material only.** An EC P-256 point, no private scalar. The private half existed for the
/// minute it took to derive this and was not written anywhere: the point of the key is that nothing
/// can sign for it, which is what makes the `is_err` assertion below a bypass search.
const PUBLIC_KEY_SET: &str = r#"{"keys":[{"kty":"EC","crv":"P-256","kid":"fuzz-seed-key","use":"sig","alg":"ES256","x":"ge0gp9sWfrleV4-8_B6u_hVpGbmJnOpKBEHy07sJEVk","y":"0b7NwSMh9mtMtfTwEV47263Ti8PbhwCV2y_6mU5_2h4"}]}"#;

/// The validator and the key set, built the only way one can be built: out of a declaration
/// `sutura-config` accepted.
///
/// A `OnceLock` rather than a rebuild per iteration - the declaration is not the input, and
/// re-parsing it would spend the fuzzer's budget on a constant. The key is fetched out of the
/// `KeySet` per iteration rather than held, so `jsonwebtoken` is not a direct dependency of this
/// crate: a second pin of it here could drift from the workspace's and the two `DecodingKey` types
/// would then be different types.
fn validator() -> &'static (TokenValidator, KeySet) {
    static BUILT: std::sync::OnceLock<(TokenValidator, KeySet)> = std::sync::OnceLock::new();
    BUILT.get_or_init(|| {
        let identity = InboundIdentity::Direct {
            resource: ResourceIdentifier::parse("https://sutura.example.com").expect("a fixture audience is one"),
            authorization_server: IssuerUrl::parse("https://issuer.example.com").expect("a fixture issuer is one"),
            key_set: KeySetFile::parse("/nonexistent/jwks.json").expect("a fixture path is one"),
            algorithms: PinnedAlgorithms::of(SigningAlgorithm::Es256),
            token_type: RequiredTokenType::access_token(),
        };
        let keys = KeySet::parse(PUBLIC_KEY_SET).expect("the fixture key set is a key set");
        (TokenValidator::new(&identity.requirement()), keys)
    })
}

/// The id of the one key in [`PUBLIC_KEY_SET`].
fn fixture_key_id() -> KeyId {
    KeyId::parse("fuzz-seed-key").expect("the fixture key id is one")
}

fuzz_target!(|data: &[u8]| {
    let presented = String::from_utf8_lossy(data);
    let (validator, keys) = validator();
    let key = keys
        .get(&fixture_key_id())
        .expect("the fixture key set holds the fixture key");

    // The pre-signature half: the header parse, on input nobody has authenticated.
    drop(TokenValidator::key_id(&presented));

    // The signature half. `Ok` here is the finding, not the panic.
    assert!(
        validator.verify(&presented, &key).is_err(),
        "a generated byte string verified against a key whose private half does not exist"
    );

    // The newtypes the post-signature half applies to claim text, driven directly - see the module
    // note on why the claims deserialization itself is out of reach.
    drop(SubjectId::parse(&presented));
    drop(Actor::parse(&presented));
});
